"""BarProcessor — orchestrates signal computation, filter evaluation, and strategy dispatch.

Maintains a rolling bar window, computes signals once per bar via SignalEngine,
evaluates filters via FilterEngine, and only calls strategies when filters pass.
"""

from __future__ import annotations

from src.core.events import BarEvent
from src.core.logging import get_logger
from src.filters.filter_engine import FilterEngine
from src.signals.signal_bundle import EMPTY_BUNDLE, SignalBundle, SignalEngine
from src.strategies.base import Signal

logger = get_logger("bar_processor")


class BarProcessor:
    """Compute signals, evaluate filters, dispatch to strategies.

    Usage:
        engine = SignalEngine(["atr", "vwap_session", "spread"])
        filters = FilterEngine.from_list([{"signal": "spread", "expr": "< 2.0"}])
        processor = BarProcessor(engine, filters, strategies)

        # Each bar:
        signals = processor.on_bar(bar)
    """

    def __init__(
        self,
        signal_engine: SignalEngine | None = None,
        filter_engine: FilterEngine | None = None,
        strategies: list | None = None,
        max_window: int = 500,
    ) -> None:
        self._signal_engine = signal_engine
        self._filter_engine = filter_engine or FilterEngine()
        self._strategies = strategies or []
        self._max_window = max_window
        self._bar_window: list[BarEvent] = []

    def on_bar(self, bar: BarEvent) -> list[Signal]:
        """Process a bar: compute signals, evaluate filters, dispatch to strategies.

        Returns list of Signal objects generated by strategies this bar.
        """
        # Maintain rolling bar window
        self._bar_window.append(bar)
        if len(self._bar_window) > self._max_window:
            self._bar_window = self._bar_window[-self._max_window:]

        # Compute signals
        if self._signal_engine is not None:
            bundle = self._signal_engine.compute(self._bar_window)
        else:
            bundle = EMPTY_BUNDLE

        # Evaluate filters
        filter_result = self._filter_engine.evaluate(bundle)
        if not filter_result.passes:
            logger.debug(
                "filters_blocked",
                reasons=filter_result.block_reasons,
            )
            return []

        # Dispatch to strategies
        signals: list[Signal] = []
        for strategy in self._strategies:
            try:
                sig = strategy.on_bar(bar, bundle)
            except TypeError:
                # Legacy strategy: on_bar(bar) without signals arg
                sig = strategy.on_bar(bar)
            except Exception:
                sid = getattr(strategy, 'strategy_id', '?')
                logger.exception("strategy_error", strategy=sid)
                continue

            if sig is not None:
                signals.append(sig)

        return signals

    def reset(self) -> None:
        """Clear bar window and reset all strategies."""
        self._bar_window.clear()
        for s in self._strategies:
            s.reset()

    @property
    def bar_window(self) -> list[BarEvent]:
        """Current bar window (read-only reference)."""
        return self._bar_window

    @property
    def bundle(self) -> SignalBundle:
        """Recompute and return the current SignalBundle (for external consumers)."""
        if self._signal_engine is not None and self._bar_window:
            return self._signal_engine.compute(self._bar_window)
        return EMPTY_BUNDLE
